"""Prompt 9 — generate the ETL vs ELT comparison from real run metrics.

Reads ``logs/pipeline_metrics.jsonl`` (appended by every stage via
``common.metrics.stage_timer``), keeps the latest run per (pipeline, stage), and
emits a comparison table (runtime per stage, totals, peak memory) plus a code-size
(LOC) proxy for code complexity. Outputs feed the report §9.

Outputs:
* ``analysis/etl_vs_elt_metrics.csv``  — machine-readable.
* ``analysis/etl_vs_elt_metrics.md``   — drop-in table for the report.

Run (pure pandas — no Spark; run after both pipelines have executed)::

    python analysis/compare_pipelines.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd  # noqa: E402

from common.logging_utils import get_logger  # noqa: E402
from common.paths import ANALYSIS_DIR, METRICS_FILE, REPO_ROOT, ensure_dirs  # noqa: E402

logger = get_logger("analysis.compare", ANALYSIS_DIR / "compare.log")

# Files whose size proxies each pipeline's code complexity.
LOC_FILES = {
    "ETL": ["etl_pipeline/transform.py", "etl_pipeline/load.py"],
    "ELT": ["elt_pipeline/extract_load.py", "elt_pipeline/run_transform.py", "elt_pipeline/transform.sql"],
}


def load_metrics() -> pd.DataFrame:
    if not METRICS_FILE.exists():
        logger.warning("No metrics file at %s — run the pipelines first.", METRICS_FILE)
        return pd.DataFrame()
    records = [json.loads(ln) for ln in METRICS_FILE.read_text(encoding="utf-8").splitlines() if ln.strip()]
    df = pd.DataFrame(records)
    if df.empty:
        return df
    # keep the latest run per (pipeline, stage)
    df = df.sort_values("ts").drop_duplicates(subset=["pipeline", "stage"], keep="last")
    return df


def loc(path: str) -> int:
    f = REPO_ROOT / path
    return len(f.read_text(encoding="utf-8").splitlines()) if f.exists() else 0


def build_table(df: pd.DataFrame) -> pd.DataFrame:
    if df.empty:
        return df
    cols = ["pipeline", "stage", "status", "rows", "duration_s", "peak_rss_mb"]
    cols = [c for c in cols if c in df.columns]
    return df[cols].sort_values(["pipeline", "stage"]).reset_index(drop=True)


def summarise(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for p in ("ETL", "ELT"):
        sub = df[df["pipeline"] == p] if not df.empty else pd.DataFrame()
        total_s = float(sub["duration_s"].sum()) if not sub.empty else None
        peak = float(sub["peak_rss_mb"].max()) if ("peak_rss_mb" in sub and not sub.empty) else None
        rows.append({
            "pipeline": p,
            "total_runtime_s": round(total_s, 3) if total_s is not None else "n/a",
            "peak_rss_mb": round(peak, 1) if peak else "n/a",
            "code_loc": sum(loc(f) for f in LOC_FILES[p]),
        })
    return pd.DataFrame(rows)


def main() -> int:
    ensure_dirs(ANALYSIS_DIR)
    df = load_metrics()
    table = build_table(df)
    summary = summarise(df)

    # CSV
    table.to_csv(ANALYSIS_DIR / "etl_vs_elt_metrics.csv", index=False)

    # Markdown
    md = ["# ETL vs ELT — measured metrics", "",
          "_Auto-generated by `analysis/compare_pipelines.py` from `logs/pipeline_metrics.jsonl`._",
          "", "## Per-stage", ""]
    md.append(table.to_markdown(index=False) if not table.empty
              else "_No metrics yet — run both pipelines, then re-run this script._")
    md += ["", "## Summary", "", summary.to_markdown(index=False)]
    (ANALYSIS_DIR / "etl_vs_elt_metrics.md").write_text("\n".join(md), encoding="utf-8")

    logger.info("Wrote etl_vs_elt_metrics.{csv,md} to %s", ANALYSIS_DIR)
    print(summary.to_string(index=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
